// Deals the BUILD injects on its own (grocery sushi days, standing value menus, dated
// owner-verified promos). Shared module (2026-09-30) so the morning refresh can see what is
// already covered and stop spending searches re-finding it. Each entry: { until, from?, dow?,
// alongside?, deal }. dow: 0=Sun..6=Sat (Eastern). Edit this file, never a generated page.
export const EVERGREEN = [
    // Owner request + officially verified (Chipotle newsroom press release, 2026-08-27):
    // one-day free double protein with code PROTEIN. Self-expires after today.
    { until: "2026-08-27", deal: { brand: "Chipotle", cat: "Bowls", color: "#a81612", ic: "Ch", deal: "Free Double Protein Today Only: Code PROTEIN", desc: "Today only (August 27): add a free second portion of meat or sofritas to any full-price burrito, bowl, or salad ordered in the Chipotle app or at chipotle.com with code PROTEIN at checkout. App and website orders only; not valid in-restaurant or on delivery platforms.", tags: ["free", "app"], value: 5, expires: "Today only, August 27", url: "https://www.chipotle.com/rewards", best: true, region: "National" } },
    // (Chipotle free-delivery evergreen removed 2026-08-25: its until-date of 2026-08-15 passed.)
    // National Quesadilla Day 2026 (owner request 2026-09-24; Chipotle newsroom release of
    // 2026-09-21): code NQD2026, Sept 24-25, US and Canada, app/website only, no Rewards
    // account required. "alongside" so a refresh-found Chipotle deal does not block it.
    { from: "2026-09-24", until: "2026-09-25", alongside: true, deal: { brand: "Chipotle", cat: "Mexican", color: "#a81612", ic: "Ch", deal: "National Quesadilla Day: Free Quesadilla with a $20 Digital Order, Code NQD2026", desc: "Thursday and Friday (September 24 to 25): add a free quesadilla entree to any Chipotle app or chipotle.com order of $20 or more with code NQD2026 at checkout. Open to everyone, no Rewards account needed. Digital orders only: not valid in restaurant or on delivery apps; no add-ons on the free quesadilla; one per order while supplies last.", tags: ["free", "app"], value: 5, est_savings: 11, expires: "Through September 25, 2026", url: "https://newsroom.chipotle.com/2026-09-21-CHIPOTLE-CELEBRATES-NATIONAL-QUESADILLA-DAY-2026-WITH-TWO-DAYS-OF-FREE-QUESADILLAS", best: true, region: "National" } },
    // Verified 2026-08-27: El Pollo Loco's $5 Fire-Grilled Combos value platform is
    // announced on the company's own investor site and current on 2026 menus.
    { until: "2026-12-31", deal: { brand: "El Pollo Loco", cat: "Chicken", color: "#f7c500", ic: "EP", deal: "$5 Fire-Grilled Combos: Rotating Value Menu", desc: "A rotating lineup of roughly $5 combos (Original Pollo Bowl, Classic Chicken Burrito, taquitos and more) built on citrus-marinated fire-grilled chicken, every day at participating locations. Lineup and pricing vary by market.", tags: [], value: 4, expires: "Ongoing", url: "https://www.elpolloloco.com/promotions", best: false, region: "West & Southwest" } },
    // Owner request (Jacob, 2026-08-14): Tijuana Flats day specials, injected only on their active weekday (dow: 0=Sun..6=Sat).
    { until: "2026-12-31", dow: 2, deal: { brand: "Tijuana Flats", cat: "Mexican", color: "#d0342c", ic: "TF", deal: "Taco Tuesdaze: 2 Tacos + Chips + Drink for $7.99", desc: "Every Tuesday at participating locations: two tacos, chips, and a drink for $7.99 in-store, online, or in the app - no third-party delivery, and pricing varies slightly by location.", tags: [], value: 4, expires: "Tuesdays only", url: "https://www.tijuanaflats.com/promotions/specials-and-deals", best: false, region: "FL & Southeast" } },
    { until: "2026-12-31", dow: 4, deal: { brand: "Tijuana Flats", cat: "Mexican", color: "#d0342c", ic: "TF", deal: "Throwback Thursdaze: Burrito or Bowl + Chips + Drink for $8.99", desc: "Every Thursday at participating locations: a Tijuana Burrito or burrito bowl plus chips and a drink for $8.99 in-store, online, or in the app - no third-party delivery; pricing varies slightly by location.", tags: [], value: 4, expires: "Thursdays only", url: "https://www.tijuanaflats.com/promotions/specials-and-deals", best: false, region: "FL & Southeast" } },
    // Owner request (Jacob, 2026-08-20): grocery-store prepared-food deals are welcome when the value is real.
    // Publix $5 Sushi Wednesday, seen in store by the owner (spicy tuna and Philadelphia rolls at his Publix);
    // confirmed by Chowhound and the AFC/Zenshi sushi counters that run it. Wednesdays only (dow 3).
    // Sprouts "Sushi Wednesday": select Oumi rolls for $5 in most markets, per the official Sprouts FAQ (2026-08-20).
    { until: "2026-12-31", dow: 3, deal: { brand: "Sprouts", cat: "Sushi", color: "#00703c", ic: "SP", deal: "Sushi Wednesday: Select Oumi Rolls for $5", desc: "Every Wednesday in most Sprouts Farmers Market locations, select Oumi sushi rolls from the in-store sushi case are $5 each instead of the regular $7 to $10. Walk in and grab them: no coupon, app, or membership needed; participation and selection vary by store.", tags: [], value: 4, expires: "Wednesdays only", url: "https://www.sprouts.com/faqs/what-is-sushi-wednesday/", best: false, region: "Select states" } },
    // Kroger-family "Wednesday Only" Private Selection sushi by Snowfox: an official kroger.com promo
    // lineup (California, Spicy Tuna, Philly, Spicy Salmon, Vegetarian and more) with a promotional
    // price on Wednesdays only; kroger.com showed $6.00 and snowfox.com says "$6 sushi every Wednesday" on 2026-09-22 (was $5).
    { until: "2026-12-31", dow: 3, deal: { brand: "Kroger", cat: "Sushi", color: "#0b3b8c", ic: "KR", deal: "Sushi Wednesday: Snowfox Promo Rolls for $6", desc: "Every Wednesday, Kroger-family stores with a Snowfox sushi counter (Kroger, Fry's, King Soopers and other banners) sell the Wednesday Only promo lineup, including spicy tuna, Philly, California and veggie rolls, for $6 a roll (up from $5 in 2025) versus $8 to $10 the rest of the week. Walk in; a free Kroger Plus card may be needed for the promo price.", tags: [], value: 4, expires: "Wednesdays only", url: "https://www.kroger.com/p/wednesday-only-private-selection-california-sushi-roll-by-snowfox-/0001111065967", best: false, region: "Select states" } },
    { until: "2026-12-31", dow: 3, alongside: true, deal: { brand: "Publix", cat: "Sushi", color: "#3d8a3a", ic: "PX", deal: "$5 Sushi Wednesday: Select Fresh Rolls for $5", desc: "Every Wednesday at Publix stores with a sushi counter, select fresh-made rolls (spicy tuna, California, spicy shrimp, cream cheese/Philadelphia-style, vegetable and more; selection varies by store) are $5 each instead of the usual $6 to $10. Walk in and grab them from the sushi case: no app, coupon, or membership needed, while supplies last.", tags: [], value: 4, expires: "Wednesdays only", url: "https://www.publix.com/savings/weekly-ad/deli", best: false, region: "FL & Southeast" } },
    // Verified 2026-08-24: Safeway's standing $5 Friday includes fresh sushi (safeway.com lists
    // dedicated "$5 Friday" sushi SKUs) plus other prepared foods; lineup posts Wednesdays in the
    // weekly ad and varies by division. Harris Teeter: $6 Sushi Friday, four Zenshi rolls, seen in
    // store by the owner in Reston, VA on 2026-10-02 (was $5 at the 2024 launch). Fridays only (dow 5).
    { until: "2026-12-31", dow: 5, deal: { brand: "Safeway", cat: "Sushi", color: "#e31837", ic: "SF", deal: "$5 Friday: Fresh Sushi Rolls for $5", desc: "Every Friday, Safeway's $5 Friday lineup includes fresh sushi rolls from the in-store counter for $5 (regularly $8 to $10), alongside other prepared-food deals like an 8-piece chicken bag. Check the weekly ad for your division; a free Safeway for U account may be needed for the promo price.", tags: [], value: 4, expires: "Fridays only", url: "https://www.safeway.com/weeklyad/", best: false, region: "Select states" } },
    { until: "2026-12-31", dow: 5, deal: { brand: "Harris Teeter", cat: "Sushi", color: "#00529b", ic: "HT", deal: "$6 Sushi Friday: California, Vegetable, Spicy Tuna and Spicy Salmon Rolls", desc: "Every Friday, Harris Teeter's Zenshi sushi counters sell four rolls for $6 each: California, Vegetable, Spicy Tuna and Spicy Salmon (regularly about $9.49 to $10.49). In store, while supplies last; the free VIC card may be needed for the promo price. Seen in store October 2, 2026.", tags: [], value: 4, est_savings: 3.5, expires: "Fridays only", url: "https://www.harristeeter.com/", best: false, region: "Southeast & Mid-Atlantic" } },
    // Added 2026-09-08 (owner request: more weekly grocery deals), each source-checked that day:
    // Hy-Vee store news pages list "Nori Sushi Roll, select varieties - $6" on Wednesdays and
    // BOGO 50% on Fridays; H-E-B's own coupon copy names "Sushi Wednesdays" and "$7 Saturdays";
    // ShopRite store pages post "$5.99 Sushi Wednesday"; Publix's order-ahead weekly specials
    // page lists the Sub of the Week. Store-run promos: descriptions say so.
    { until: "2026-12-31", dow: 3, deal: { brand: "Hy-Vee", cat: "Sushi", color: "#e31837", ic: "HV", deal: "Sushi Wednesday: Select Nori Sushi Rolls for $6", desc: "Every Wednesday at participating Hy-Vee stores with a Nori Sushi counter, select rolls are $6 each (regularly about $8 to $10). A store-run promotion: some stores run buy one, get one 50% off instead, so price and selection vary by store; no card or app is needed.", tags: [], value: 3, expires: "Wednesdays only", url: "https://www.hy-vee.com/deals/weekly-ads", best: false, region: "Midwest" } },
    { until: "2026-12-31", dow: 5, deal: { brand: "Hy-Vee", cat: "Sushi", color: "#e31837", ic: "HV", deal: "Sushi Friday: Buy One Nori Roll, Get One 50% Off", desc: "Every Friday at participating Hy-Vee stores, buy one regular Nori Sushi roll and get a second at half price. Store-run promotion: participation varies, no card or app needed.", tags: [], value: 3, expires: "Fridays only", url: "https://www.hy-vee.com/deals/weekly-ads", best: false, region: "Midwest" } },
    { until: "2026-12-31", dow: 3, deal: { brand: "H-E-B", cat: "Sushi", color: "#e01e26", ic: "HB", deal: "Sushi Wednesday: Select Sushiya Rolls for $7", desc: "Every Wednesday, H-E-B stores with an in-store Sushiya counter sell select fresh rolls for $7 (regularly about $9 to $12). No coupon or app needed; selection varies by store and sells out by evening.", tags: [], value: 3, expires: "Wednesdays only", url: "https://www.heb.com/category/shop/deli-prepared-food/ready-meals-snacks/sushi/490061/490236", best: false, region: "Texas" } },
    { until: "2026-12-31", dow: 6, deal: { brand: "H-E-B", cat: "Sushi", color: "#e01e26", ic: "HB", deal: "$7 Saturday: Select Sushiya Rolls for $7", desc: "H-E-B's Sushiya counters repeat the $7 select-roll price on Saturdays at participating Texas stores. No coupon or app needed; selection varies by store.", tags: [], value: 3, expires: "Saturdays only", url: "https://www.heb.com/category/shop/deli-prepared-food/ready-meals-snacks/sushi/490061/490236", best: false, region: "Texas" } },
    { until: "2026-12-31", dow: 3, deal: { brand: "ShopRite", cat: "Sushi", color: "#c8102e", ic: "SR", deal: "$5.99 Sushi Wednesday: Select Rolls", desc: "Every Wednesday, participating ShopRite stores sell select fresh sushi rolls (spicy crab, California and more) for $5.99, regularly $8 to $10. In-store only; ShopRite stores are independently owned, so selection and participation vary.", tags: [], value: 3, expires: "Wednesdays only", url: "https://www.shoprite.com/categories/prepared-foods/sushi-seafood-id-520585", best: false, region: "NJ, NY, PA, CT, DE & MD" } },
    // MORE SUSHI DAYS (owner request 2026-09-22, "more good value sushi deals"). Each one was
    // verified that day on an official channel (the chain's own site or its verified page,
    // or the vendor program built for that chain). Meijer, Giant Food, Giant Eagle, Stop &
    // Shop and Fresh Thyme could NOT be pinned to an official current price and stay out.
    { until: "2026-12-31", dow: 3, deal: { brand: "Weis Markets", cat: "Sushi", color: "#c8102e", ic: "W", deal: "$5 Sushi Wednesday: Select Snowfox Rolls", desc: "Every Wednesday, Weis Markets stores with a Snowfox sushi counter sell selected rolls, as marked in the case, for $5 each (regularly $7 to $9). In store only, no card or app needed, while supplies last.", tags: [], value: 3, expires: "Wednesdays only", url: "https://www.weismarkets.com/weekly-ad", best: false, region: "PA, MD, NY, NJ, DE, WV & VA" } },
    { until: "2026-12-31", dow: 3, deal: { brand: "Food Lion", cat: "Sushi", color: "#1a4c9c", ic: "FL", deal: "$5 Sushi Wednesday: Select Hissho Rolls", desc: "Every Wednesday, Food Lion stores with a Hissho sushi counter sell select fresh rolls for $5 each (regularly $7 to $9). Grab them from the sushi case during counter hours; no card, coupon or app needed, while supplies last.", tags: [], value: 3, expires: "Wednesdays only", url: "https://www.foodlion.com/savings/weekly-ad", best: false, region: "Mid-Atlantic & Southeast" } },
    { until: "2026-12-31", dow: 3, deal: { brand: "Lowes Foods", cat: "Sushi", color: "#e4002b", ic: "LF", deal: "Sushi Wednesday: Select Fresh Rolls for $4.99", desc: "Every Wednesday, Lowes Foods sells select hand-rolled sushi from its in-store counter for $4.99 a roll (regularly $7 to $9). In store, no card or app needed, while supplies last.", tags: [], value: 3, expires: "Wednesdays only", url: "https://www.lowesfoods.com/savings-and-rewards/weekly-ad", best: false, region: "NC & SC" } },
    { until: "2026-12-31", dow: 3, deal: { brand: "Hannaford", cat: "Sushi", color: "#7a1f1f", ic: "H", deal: "$5 Sushi Wednesday: California, Spicy California & Vegan Rolls", desc: "Every Wednesday, Hannaford's Wago sushi counters sell the California, Spicy California and Classic Vegan rolls for $5 each (regularly $7 to $8). In store only, no card or app needed, while supplies last.", tags: [], value: 3, expires: "Wednesdays only", url: "https://www.wagosushi.com/faqs/", best: false, region: "ME, NH, VT, MA & NY" } },
    { until: "2026-12-31", dow: 2, deal: { brand: "Dierbergs", cat: "Sushi", color: "#00703c", ic: "D", deal: "Sushi Tuesday: Select Rolls for $6", desc: "Every Tuesday, Dierbergs sells select varieties of its hand-rolled Bento sushi for $6 each (regularly $8 to $10). In store, no card or app needed, while supplies last.", tags: [], value: 3, expires: "Tuesdays only", url: "https://www.dierbergs.com/department/deli-and-prepared-foods", best: false, region: "St. Louis area" } },
    // Island Fin Poke publishes Topping Tuesday on its own Daily Specials page (verified 2026-09-22).
    { until: "2026-12-31", dow: 2, deal: { brand: "Island Fin Poke", cat: "Poke", color: "#0e8c8c", ic: "IF", deal: "Topping Tuesday: Free Premium Topping with Any Bowl", desc: "Every Tuesday, pick one premium topping (avocado, kimchi, masago, surimi and more, normally an upcharge) free with any poke bowl. Ask at the counter; no app, code or account needed.", tags: [], value: 2, expires: "Tuesdays only", url: "https://www.islandfinpoke.com/custom-content-1/", best: false, region: "FL & Select states" } },
    // Pokeworks September codes, from the chain's own 2026-09-02 press release (open to all
    // guests, in store and online). Each self-expires.
    { from: "2026-09-21", until: "2026-09-27", deal: { brand: "Pokeworks", cat: "Poke", color: "#1b3a6b", ic: "PW", deal: "Free Extra Scoop of Ahi or Chicken with Code POWERUP", desc: "Through September 27, order the High-Protein Surf & Turf bowl and add a free extra scoop of ahi tuna or chicken with code POWERUP, in store or online. Open to all guests, no rewards account needed.", tags: [], value: 4, expires: "Through September 27, 2026", url: "https://pokeworks.com/rewards/", best: false, region: "Select states" } },
    { from: "2026-09-28", until: "2026-09-30", deal: { brand: "Pokeworks", cat: "Poke", color: "#1b3a6b", ic: "PW", deal: "International Poke Day: Free Extra Protein Scoop with Code POKEDAY", desc: "September 28 to 30, get a free extra scoop of protein with any regular or large poke entree using code POKEDAY, in store or online. Open to all guests, no rewards account needed.", tags: [], value: 4, expires: "Through September 30, 2026", url: "https://pokeworks.com/rewards/", best: false, region: "Select states" } },
    { until: "2026-12-31", deal: { brand: "Publix", cat: "Deli", color: "#3d8b37", ic: "PX", deal: "Sub of the Week: $2 Off This Week's Featured Whole Sub", desc: "Every week Publix takes $2 off one featured whole deli sub (a Boar's Head turkey sub or the Publix Deli Ultimate Sub, for example, about $8.99 instead of $10.99), fully customizable at the counter, online or in the app. The featured sub changes with the weekly ad; the deli's weekly specials page lists it.", tags: [], value: 3, expires: "Ongoing (changes weekly)", url: "https://www.publix.com/mc/order-ahead/weekly-specials", best: false, region: "FL & Southeast" } },
    // VALUE-MENU FLOOR (2026-09-15, cost + depth pass; Subway removed 2026-09-21, see
    // STANDING_MENU_BLOCK below). These standing value menus
    // were verified by the refresh itself on 2026-09-08 (titles, prices and URLs copied
    // from that run's deals.json) but only re-found on some days, so the list swung
    // between 8 and 11. Injected only when the morning refresh misses the brand (the
    // one-per-brand rule, no "alongside"), so a fresher refresh-found entry always wins.
    // Each expires 2026-10-15: re-verify the price then and bump the date, or drop it.
    { until: "2026-10-15", deal: { brand: "Salad and Go", cat: "Salads", color: "#6cbf3e", ic: "SnG", deal: "Salads and wraps from $7.75", desc: "Drive-thru-only salads and wraps, including the Good Greens Salad and Wrap with chickpeas, Brussels sprouts and a choice of chicken or tofu, start at $7.75 every day.", tags: [], value: 3, expires: "Ongoing", url: "https://saladandgo.com/menu", est_savings: 3, best: false, region: "AZ, TX, OK & NV" } },
    { until: "2026-10-15", deal: { brand: "Rubio's Coastal Grill", cat: "Seafood", color: "#00a1e0", ic: "R", deal: "$7+ Meal Menu, including Fish & Chips for $7.99", desc: "Rubio's standing value menu runs meals from $7 to $10, headlined by Fish & Chips for $7.99, every day at participating locations.", tags: [], value: 3, expires: "Ongoing", url: "https://www.rubios.com/menu", est_savings: 3, best: false, region: "CA, AZ & NV" } },
    { until: "2026-10-15", deal: { brand: "WaBa Grill", cat: "Bowls", color: "#e4002b", ic: "W", deal: "Value-Bowl Combo: mini bowl, side and drink for $7.99", desc: "A permanent value item: a mini bowl with chicken, sweet and spicy chicken or tofu, plus a value side and a 12 oz drink for $7.99, every day at participating locations.", tags: [], value: 3, expires: "Ongoing", url: "https://www.wabagrill.com/menu", est_savings: 3, best: false, region: "CA & AZ" } },
    { until: "2026-10-15", deal: { brand: "Naf Naf Grill", cat: "Mediterranean", color: "#c8102e", ic: "N", deal: "$9.99 Pita Meal Deal", desc: "Naf Naf Grill's value menu: a full pita meal for $9.99, in store and in the app, every day at participating locations.", tags: ["app"], value: 3, expires: "Ongoing", url: "https://nafnafgrill.com/", est_savings: 3, best: false, region: "Midwest & East" } },
    // Dated promo (owner request, 2026-09-11). Verified the same day on the chain4s own
    // offer-terms page, which reads "Rewards Members enjoy 2 regular sized noodle bowls
    // from the Culinary Classic category for $12" - note "Rewards Members", NOT the
    // "Select Rewards Members" wording that keeps the NFL free-side offer off the site.
    // Noodles Rewards is free to join, so this clears FREE ACCOUNTS ARE FINE. It runs
    // alongside the standing Delicious Duos entry and self-expires after 9/14.
    { from: "2026-09-10", until: "2026-09-14", alongside: true, deal: { brand: "Noodles & Company", cat: "Bowls", color: "#8dc63f", ic: "N", deal: "2 Culinary Classics Bowls for $12", desc: "Two regular-size bowls from the Culinary Classics menu for $12 together, about $19 bought separately: Pad Thai, Japanese Pan Noodles, Pasta Fresca, Basil Pesto Cavatappi, Creamy Cheddar Mac, Buttered Noodles or either tortelloni. Free Noodles Rewards account required: apply the offer on the cart screen before checkout, or scan at the register. Proteins and add-ons cost extra, one per account, at participating locations, and not valid on third-party delivery, call-in or catering orders.", tags: ["app"], value: 4, expires: "Through September 14, 2026", url: "https://www.noodles.com/offer-terms", est_savings: 7, best: false, region: "National" } },
    // Potbelly Week of Perks (owner request, 2026-09-30). Fifth annual event, Sep 28 to Oct 2,
    // a different deal each day for Potbelly Perks members (free account), announced in the
    // app each morning; DealNews (2026-09-28) lists buy-one-get-one 50% off entrees among
    // them. Sources: potbelly.com/perks, the 2026-09-16 press release (franchising.com),
    // QSR Magazine. Self-expires after 10/2. Potbelly is the closest roster chain to the owner.
    { from: "2026-09-30", until: "2026-10-02", deal: { brand: "Potbelly", cat: "Deli", color: "#7a1c1c", ic: "PB", deal: "Week of Perks: BOGO 50% Off Entrees and a New Deal Every Day Through October 2", desc: "Potbelly's fifth annual Week of Perks runs September 28 to October 2: a different deal each day for Potbelly Perks members (free account required), announced in the app each morning, including buy-one-get-one 50% off entrees. Order in the app, on potbelly.com, or scan your Perks account in shop.", tags: ["app"], value: 4, expires: "Through October 2, 2026", url: "https://www.potbelly.com/perks", best: false, region: "Select states", est_savings: 5 } },
    // Weekly loyalty special (owner rule 2026-09-30: allowed on its day). Smoothie King's rewards
    // terms name Free Upsize Fridays and say Healthy Rewards is free to join (smoothieking.com,
    // checked 2026-10-02); the size terms are from Smoothie King's own posts and Sept 2026 trackers.
    { until: "2026-12-31", dow: 5, deal: { brand: "Smoothie King", cat: "Smoothies", color: "#c8102e", ic: "SK", deal: "Free Upsize Friday: 32 oz Smoothie for the Price of a 20 oz", desc: "Every Friday, Healthy Rewards members (free account required) get a 32 oz smoothie for the price of a 20 oz when they order in the Smoothie King app, at participating locations. Rewards cannot be redeemed on these orders.", tags: ["app"], value: 3, expires: "Fridays only", url: "https://www.smoothieking.com/rewards/", best: false, region: "National" } },
    // ---- Added 2026-10-03 (owner: the Saturday list had nothing but standing deals). Sources:
    // starbucks.com homepage and about.starbucks.com (Free Mod Monday, Rewards members, up to
    // $2.25); the rest from The Krazy Coupon Lady's food-deals roundup updated 2026-10-02, a
    // tracker the refresh rules accept. Each entry is date- or weekday-gated so it self-expires.
    { from: "2026-10-05", until: "2026-10-05", deal: { brand: "Starbucks", cat: "Cafe", color: "#00704a", ic: "SB", deal: "Free Mod Monday: One Drink Customization Free, Up to $2.25", desc: "Monday, October 5 only: Starbucks Rewards members (free account required) get one drink customization free, up to $2.25 before tax: an extra espresso shot, a syrup or sauce, cold foam, protein cold foam or protein-boosted milk. Apply it in the app or ask the barista; not combinable with other Rewards or offers. Starbucks says members get one free customization each month.", tags: ["app"], value: 2, expires: "Monday, October 5 only", url: "https://www.starbucks.com/", best: false, region: "National", est_savings: 2.25 } },
    { from: "2026-10-06", until: "2026-10-06", deal: { brand: "Honeygrow", cat: "Bowls", color: "#e8572a", ic: "HG", deal: "National Noodle Day: Buy One Stir-Fry, Get One Free", desc: "Tuesday, October 6 only: Honeygrow rewards members (free account required) get a second stir-fry free with the purchase of one, ordering online or in the app. Listed by The Krazy Coupon Lady on October 2, 2026; confirm in the app before you order.", tags: ["app"], value: 5, expires: "Tuesday, October 6 only", url: "https://www.honeygrow.com/", best: false, region: "Northeast & Mid-Atlantic", est_savings: 12 } },
    { until: "2026-12-31", dow: 2, deal: { brand: "Saladworks", cat: "Salads", color: "#6cbf3e", ic: "SLW", deal: "Tuesday Deal: Build-Your-Own Salad or Wrap for $6.99", desc: "Every Tuesday, a build-your-own base salad or wrap is $6.99 at participating Saladworks locations. Listed by The Krazy Coupon Lady on October 2, 2026; check your location before you go.", tags: [], value: 3, expires: "Tuesdays only", url: "https://saladworks.com/", best: false, region: "Northeast & Mid-Atlantic", est_savings: 3 } },
    { until: "2026-12-31", dow: 1, alongside: true, deal: { brand: "El Pollo Loco", cat: "Chicken", color: "#f7c500", ic: "EP", deal: "Loco Rewards Monday: Chips and Guacamole for $1 with an $11.99 Order", desc: "Every Monday, Loco Rewards members (free account required) get regular chips and guacamole for $1 with a purchase of $11.99 or more; the offer drops in the app on Mondays, one per member per week. Listed by The Krazy Coupon Lady on October 2, 2026.", tags: ["app"], value: 3, expires: "Mondays only", url: "https://www.elpolloloco.com/promotions", best: false, region: "West & Southwest", est_savings: 3 } },
    { from: "2026-10-03", until: "2026-10-26", deal: { brand: "Subway", cat: "Sandwiches", color: "#008c15", ic: "SUB", deal: "BOGO 50% Off Footlongs with Code BOGO50", desc: "Buy one footlong online or in the Subway app and get a second 50% off with code BOGO50 at participating locations. Listed by The Krazy Coupon Lady on October 2, 2026; the code has run since summer and may end without notice, so enter it before paying.", tags: ["app"], value: 4, expires: "Limited time", url: "https://www.subway.com/en-us", best: false, region: "National", est_savings: 4 } },
];

// Entries the build will inject for a given Eastern date (iso YYYY-MM-DD) and weekday index.
export function injectedToday(iso, dow) {
  return EVERGREEN.filter(e => (e.dow === undefined || e.dow === dow) && !(e.from && iso < e.from) && iso <= e.until).map(e => e.deal);
}
